# Generated by Django 5.2 on 2025-05-12 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=200, null=True)),
                ('business_registration_number', models.CharField(max_length=100, unique=True)),
                ('business_type', models.CharField(blank=True, max_length=100, null=True)),
                ('classification', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('alternative_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('headquarters_address', models.TextField(blank=True, null=True)),
                ('working_hours', models.JSONField(blank=True, help_text='Store working hours in JSON format', null=True)),
                ('trade_license', models.FileField(blank=True, null=True, upload_to='vendor_documents/trade_licenses/')),
                ('tax_certificate', models.FileField(blank=True, null=True, upload_to='vendor_documents/tax_certificates/')),
                ('business_registration_document', models.FileField(blank=True, null=True, upload_to='vendor_documents/registration_docs/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('branches', models.JSONField(blank=True, help_text='Store branch information in JSON format', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_vendors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Profile',
                'verbose_name_plural': 'Vendor Profiles',
                'unique_together': {('user', 'business_registration_number')},
            },
        ),
    ]
