# Generated by Django 5.2 on 2025-05-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_vendorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='classification',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('special', 'Special')], default='bronze', max_length=20),
        ),
    ]
