# Generated by Django 5.2 on 2025-05-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_timeperiodcommission_offertypecommission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendortypecommission',
            name='vendor_classification',
            field=models.CharField(choices=[('bronze', 'Bronze (20%)'), ('silver', 'Silver (15%)'), ('gold', 'Gold (10%)'), ('platinum', 'Platinum (5%)'), ('special', 'Special (Custom)')], max_length=20),
        ),
    ]
