# Generated by Django 5.2 on 2025-05-15 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_alter_vendortypecommission_vendor_classification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendortypecommission',
            unique_together={('is_active',)},
        ),
    ]
