# Generated by Django 5.2 on 2025-05-15 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_alter_vendortypecommission_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendortypecommission',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='vendortypecommission',
            name='vendor_classification',
            field=models.CharField(choices=[('bronze', 'Bronze (20%)'), ('silver', 'Silver (15%)'), ('gold', 'Gold (10%)'), ('platinum', 'Platinum (5%)'), ('special', 'Special (Custom)')], max_length=20, unique=True),
        ),
        migrations.AddConstraint(
            model_name='vendortypecommission',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('vendor_classification', 'is_active'), name='unique_active_classification'),
        ),
    ]
