# Generated by Django 5.2 on 2025-05-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_alter_vendortypecommission_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendortypecommission',
            name='vendor_classification',
            field=models.CharField(choices=[('bronze', 'Bronze (Default: 20%)'), ('silver', 'Silver (Default: 15%)'), ('gold', 'Gold (Default: 10%)'), ('platinum', 'Platinum (Default: 5%)'), ('special', 'Special (Custom)')], max_length=20, unique=True),
        ),
    ]
